In [19]:
from nltk.tree import Tree

import pandas as pd

from nltk.corpus.reader.wordnet import Lemma
from nltk.corpus import wordnet as wn
from nltk.stem import WordNetLemmatizer
import numpy as np


from scipy.stats import spearmanr, pearsonr

In [3]:
tokens_df = pd.read_csv('./collected_tokens/semcor/all_tokens.csv')
tokens_df

,lemma,sense,word_form,sentence_id,pos
0,dancing school,Lemma('dancing_school.n.01.dancing_school'),dancing,2030,NN
1,dancing school,Lemma('dancing_school.n.01.dancing_school'),school,2030,NN
2,so,Lemma('so.r.01.so'),so,2030,RB
3,artistic,Lemma('artistic.a.01.artistic'),artistic,2030,JJ
4,psychological,Lemma('psychological.s.01.psychological'),psychological,2030,JJ
...,...,...,...,...,...
242636,thyroid,Lemma('thyroid_gland.n.01.thyroid'),thyroid,3959,NN
242637,oxidised,Lemma('oxidize.v.02.oxidise'),oxidised,3959,VB
242638,re-incorporated,Lemma('re-incorporate.v.01.re-incorporate'),re-incorporated,3959,VB
242639,thyroglobulin,Lemma('thyroglobulin.n.01.thyroglobulin'),thyroglobulin,3959,NN
242640,lead,Lemma('conduct.v.02.lead'),lead,27662,VB

In [14]:

# Group by lemma and sense, then count distinct token_ids
grouped = tokens_df.groupby(['lemma', 'sense'])['sentence_id'].nunique().reset_index()

# Keep only lemma groups with at least 5 distinct token_ids per sense
valid_senses = grouped[grouped['sentence_id'] >= 20]

# Count how many senses each lemma has after filtering
lemma_counts = valid_senses.groupby('lemma')['sense'].nunique()

# Keep only lemmas that have at least two distinct senses
valid_lemmas = lemma_counts[lemma_counts >= 2].index


# Filter the original DataFrame
filtered_df = tokens_df[tokens_df['lemma'].isin(valid_lemmas)]

good_lemmas = filtered_df['lemma'].unique()
len(good_lemmas)

259

In [15]:
filtered_df.head()

,lemma,sense,word_form,sentence_id,pos
2,so,Lemma('so.r.01.so'),so,2030,RB
5,development,Lemma('development.n.02.development'),development,2030,NN
9,early,Lemma('early_on.r.01.early'),early,2030,RB
17,put,Lemma('lay.v.02.put_down'),put,10375,VB
20,girl,Lemma('girl.n.01.girl'),girl,10375,NN

In [12]:
good_lemmas

array(['so', 'development', 'put', 'girl', 'said', 'made', 'then',
       'making', 'is', 'surface', 'now', 'time', 'end', 'first', 'were',
       'treatment', 'feed', 'two', 'at least', 'voice', 'are', 'been',
       'say', 'foot', 'one', 'question', 'ask', 'wrote', 'death', 'go',
       'mean', 'still', 'just', 'given', 'long', 'show', 'wa', 'public',
       'know', 'work', 'done', 'place', 'new', 'asked', 'left', 'be',
       'reported', 'man', 'came', 'see', 'form', 'last', 'thought',
       'need', 'became', 'come', 'being', 'alone', 'high', 'appeared',
       'only', 'here', 'had', 'took', 'thing', 'remember', 'amount',
       'described', 'case', 'become', 'get', 'life', 'give', 'find',
       'area', 'have', 'better', 'job', 'little', 'told', 'most', 'major',
       'found', 'more', "'s", 'well', 'got', 'same', 'material', 'knew',
       'do', 'use', 'stopped', 'gave', 'like', 'united states', 'added',
       'month', 'take', 'word', 'great', 'play', 'suddenly', 'reason',
       'full', 'program', 'various', 'past', 'too', 'fact', 'change',
       'number', 'held', 'feel', 'problem', 'country', 'make', 'interest',
       'cell', 'present', 'cost', 'figure', 'church', 'ha', 'men', 'day',
       'experience', 'information', 'tell', 'enough', 'look', 'different',
       'known', 'step', 'increased', 'family', 'old', 'return', 'much',
       'american', 'really', 'table', 'think', 'meaning', 'matter', 'way',
       'seen', 'section', 'thus', 'back', 'plant', 'increase', 'rather',
       'activity', 'no', 'heard', 'basis', 'world', 'felt', 'child',
       'appear', 'moment', 'pressure', 'seems', 'shown', 'becomes',
       'door', 'value', 'looked', 'quite', 'needed', 'learned', 'home',
       'individual', 'believe', 'feeling', 'designed', 'created',
       'indicated', 'le', 'water', 'rate', 'state', 'property'],
      dtype=object)

In [25]:
# pick a few random groups
# Set random seed for reproducibility
np.random.seed(42)

# Randomly select 10 unique lemmas
selected_lemmas = np.random.choice(filtered_df['lemma'].unique(), size=50, replace=False)
selected_lemmas

array(['only', 'done', 'is', 'amount', 'permit', 'knew', 'child', 'home',
       'various', 'kept', 'find', 'still', 'consider', 'here', 'place',
       'stopped', 'made', 'death', 'got', 'form', 'say', 'special',
       'pattern', 'think', 'heart', 'were', 'feel', 'needed', 'feeling',
       'final', 'at least', 'face', 'hear', 'basis', 'surface', 'gave',
       'became', 'play', 'told', 'foot', 'described', 'two', 'church',
       'catholic', 'back', 'act', 'manager', 'seen', 'down', 'leave'],
      dtype=object)

In [26]:

# Filter the DataFrame to keep only the selected lemmas
polysemous_sample = filtered_df[filtered_df['lemma'].isin(selected_lemmas)]
len(polysemous_sample)

15065

In [27]:
# save to disk
filtered_df.to_csv('./collected_tokens/semcor/polysemous_tokens.csv', index=False)